message(${CMAKE_HOST_SYSTEM_NAME})

MESSAGE(STATUS "operation system is ${CMAKE_SYSTEM}")
IF(CMAKE_SYSTEM_NAME MATCHES "Linux")
    set(SYSTEM_NAME "linux")
    MESSAGE(STATUS "current platform: Linux ")
ELSEIF(CMAKE_SYSTEM_NAME MATCHES "Windows")
    set(SYSTEM_NAME "win32")
    MESSAGE(STATUS "current platform: Windows")
ELSEIF(CMAKE_SYSTEM_NAME MATCHES "FreeBSD")
    set(SYSTEM_NAME "freeebsd")
    MESSAGE(STATUS "current platform: FreeBSD")
ELSE()
    set(SYSTEM_NAME "unknown")
    MESSAGE(STATUS "other platform: ${CMAKE_SYSTEM_NAME}")
ENDIF()

IF(WIN32)
    MESSAGE(STATUS "Now is windows")
ELSEIF(APPLE)
    MESSAGE(STATUS "Now is Apple systens.")
ELSEIF(UNIX)
    MESSAGE(STATUS "Now is UNIX-like OS's. Including aPPLE os x  and CygWin")
ENDIF()

MESSAGE(${CMAKE_SYSTEM})
MESSAGE(${CMAKE_SYSTEM_NAME})
MESSAGE(${CMAKE_SYSTEM_VERSION})
MESSAGE(${CMAKE_SYSTEM_PROCESSOR})

